version: '3.4'

services:
  plutus.web:
    container_name: plutus-web
    image: "${DOCKER_REGISTRY-}isanjay112/plutus-web:latest"
    ports:
    - 4200:4200
    
  plutus.restapi:
    container_name: plutus-api
    image: "${DOCKER_REGISTRY-}plutusapi:latest"
    build:
      context: .
      dockerfile: Plutus.Api/Dockerfile
    depends_on:
      database-server:
        condition: service_healthy
    environment:
      - PGPASSWORD=${PG_PASSWORD}
      - PGUSER=${PG_USER}
      - PGDATABASE=${PG_DATABASE}
      - PGHOST=${PG_HOST}
    ports:
      - 5000:80
      

  database-server:
    image: postgres:13
    container_name: plutus-database
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_DB=${PG_DATABASE}
    ports:
      - 5432:5432
    volumes:
    - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 5